CREATE TABLE IF NOT EXISTS transaction_events (
    id                BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id          VARCHAR(255)    NOT NULL,
    account_id        VARCHAR(255)    NOT NULL,
    type              VARCHAR(50)     NOT NULL,
    amount            DECIMAL(19, 4)  NOT NULL,
    currency          VARCHAR(10)     NOT NULL,
    event_timestamp   TIMESTAMP       NOT NULL,
    metadata          CLOB,
    received_at       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_event_id UNIQUE (event_id)
);

CREATE INDEX IF NOT EXISTS idx_te_account_id
    ON transaction_events (account_id);

CREATE INDEX IF NOT EXISTS idx_te_event_timestamp
    ON transaction_events (event_timestamp);
